children:
  - Virginia
  - Evelyn
  - Lucy
chores:
db: "chore_chart.db"  
schema: "schema.sql"
behavior:
  'Bad Behavior': -.25
  'Very Bad Behavior': -1
hourly_rate: 12
minimum_rate: .25
minimum_deduct: -.25