version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://chorechamp:${POSTGRES_PASSWORD}@db:5432/chorechamp
      - SESSION_SECRET=${SESSION_SECRET:-default_secret_change_me}
    volumes:
      - ./static:/app/static

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=chorechamp
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-chorechampdefault}
      - POSTGRES_DB=chorechamp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: