FROM python:3.11-slim

# Work directory
WORKDIR chore_tracker/app


# Set environment variables
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV FLASK_RUN_PORT=5000
ENV PYTHONUNBUFFERED=1

EXPOSE 5000

CMD ["sh", "-c", "flask init-db && flask init-users && flask init-chores && flask run"]
